version: '3'
services:
  scraper:
    build: ./scraper
    environment:
      - ELASTIC_ENABLE=true
      - PATHS_ORL=/workspace/data
      - PATHS_CHANNELS=/workspace/channels.txt
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
    volumes:
      - ${HOST_ORL_PATH:-./orl}:/workspace/data
      - ./channels.txt:/workspace/channels.txt
    network_mode: host
    restart: unless-stopped
  rustlesearch:
    build: ./go-api
    environment:
      - VIP_ENV=production
      - VIP_PATHS_ORL=/workspace/data
      - VIP_PATHS_CHANNELS=/workspace/channels.txt
    volumes:
      - ${HOST_ORL_PATH:-./orl}:/workspace/data
      - ./channels.txt:/workspace/channels.txt
    network_mode: host
    restart: unless-stopped
