version: '3'
services:
  scraper:
    build: ./scraper
    environment:
      - ELASTIC_ENABLE=true
      - PATHS_ORL=/workspace/data
      - PATHS_CHANNELS=/workspace/channels.json
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
    volumes:
      - ./orl:/workspace/data
      - ./channels.json:/workspace/channels.json
    network_mode: host
    restart: unless-stopped
  rustlesearch:
    build: ./go-api
    environment:
      - VIP_ENV=production
      - VIP_PATHS_ORL=/orl
    volumes:
      - ${HOST_ORL_PATH:-./orl}:/orl
    network_mode: host
    restart: unless-stopped
