version: "3"

services:
  rustlesearch:
    image: rustlesearch:latest
    build:
      context: .
    env_file: .env
    environment:
      - VIP_ENV=production
      - VIP_PATHS_ORL=/orl
    ports:
      - ${VIP_SERVER_PORT:-3000}:${VIP_SERVER_PORT:-3000}
    volumes:
      - ${HOST_ORL_PATH:-../scripts/data/orl}:/orl
    network_mode: host
    restart: unless-stopped

